"""
policy_exporter.py — converts a DistilledGraph (v1.1) to a .policy scaffold file.

Output contract:
  - First line: # is_valid_ctm_graph: false
  - Every BLOCKING gap: # GOVERNANCE GAP: {category} — BLOCKING — layer: {layer}
  - Every diagnostic: # DIAGNOSTIC: {explanation}
  - No # SUGGESTION: lines anywhere
  - No rule keyword as filled content
  - No actor names or condition values as proposals
  - All governance placeholders are empty blocks
  - v2.0: actors {} block populated with inferred IDs from actor_graph,
    marked ACTOR_SCOPE_INFERRED — ADVISORY

§48 boundary: imports only stdlib.
"""
from __future__ import annotations

_HEADER = """\
# CTM-PFSD Policy Scaffold — generated by Eleutherios Distiller v1.1
# is_valid_ctm_graph: false — this file requires human governance authorship
# schema_version: {schema_version}
# All GOVERNANCE GAP markers require human authorship to resolve
# All DIAGNOSTIC entries describe why the gap exists — not how to fill it
#
# project: {project_name}
# modules: {policies_count}  services: {services_count}  gaps: {gaps_total}
"""

_NAMESPACE = """\

namespace {namespace}.governance

"""

_ACTORS_BLOCK = """\
# GOVERNANCE GAP: ACTOR_SCOPE — BLOCKING — layer: WHY
# DIAGNOSTIC: Actor hierarchy cannot be derived from source code.{actor_diagnostics}
actors {{ }}

"""

_ACTORS_BLOCK_V2 = """\
# GOVERNANCE GAP: ACTOR_SCOPE_INFERRED — ADVISORY — layer: WHY
# DIAGNOSTIC: Actor hierarchy inferred from file boundaries only.
# File boundary does not equal policy boundary. Human authorship
# required to confirm or restructure this actor hierarchy.{actor_diagnostics}
actors {{
{actor_ids}}}

"""

_POLICY_OPEN = """\
# GOVERNANCE GAP: POLICY_OWNERSHIP — BLOCKING — layer: WHY
# DIAGNOSTIC: Policy authority requires human authorship.{policy_diagnostics}
policy {policy_name} {{
  actor_scope: [ ]

"""

_POLICY_CLOSE = """\
}}

"""

_RULE_PLACEHOLDER = """\
  # RULE PLACEHOLDER — requires human authorship
  # GOVERNANCE GAP: RULE_CONDITION — BLOCKING — layer: WHAT
  # DIAGNOSTIC: Rule condition cannot be inferred from service signature alone.{rule_diagnostics}

"""

_SERVICE_BLOCK = """\
# SERVICE PLACEHOLDER — inferred from code (HOW layer only)
# This is not a valid CTM service definition — schema incomplete
service {service_name} {{
  # source: {source_name}() at line {line_number}
  # GOVERNANCE GAP: SERVICE_SCHEMA — BLOCKING — layer: HOW
  # DIAGNOSTIC: Python type hint is not a CTM-PFSD service schema.
  # GOVERNANCE GAP: SERVICE_ENDPOINT — BLOCKING — layer: HOW
  # DIAGNOSTIC: Service endpoint requires human authorship.{service_diagnostics}
  schema: {{ }}
  simulation_safe: /* requires human authorship */
}}

"""


def _format_diagnostics(diagnostics: list, indent: str = "") -> str:
    """Format extra diagnostics as comment lines (beyond the standard gap comments)."""
    lines = []
    for d in diagnostics:
        if d.get("source") == "llm_v1":
            lines.append(
                f"\n{indent}# DIAGNOSTIC (llm_v1, {d.get('confidence', 0):.0%}): "
                f"{d.get('explanation', '')}"
            )
    return "".join(lines)


def _slugify_namespace(name: str) -> str:
    import re
    return re.sub(r"[^a-z0-9_]", "_", name.lower()).strip("_")


class PolicyExporter:

    def export(self, graph: dict) -> str:
        """
        Convert a DistilledGraph dict to a .policy scaffold string.
        """
        schema_version = graph.get("schema_version", "1.1")
        project_name   = graph.get("project_name", "project")
        summary        = graph.get("summary", {})
        nodes          = graph.get("nodes", [])
        edges          = graph.get("edges", [])

        # Build adjacency: parent → [children]
        children_of: dict = {}
        for e in edges:
            children_of.setdefault(e["from"], []).append(e["to"])
        node_by_id = {n["id"]: n for n in nodes}

        root = node_by_id.get(graph.get("root_policy_id", ""))
        module_p_nodes = [
            node_by_id[cid]
            for cid in children_of.get(root["id"] if root else "", [])
            if node_by_id.get(cid, {}).get("type") == "P"
        ] if root else [
            n for n in nodes
            if n["type"] == "P" and not n["meta"].get("is_root")
        ]

        out = []

        # Header
        out.append(_HEADER.format(
            schema_version = schema_version,
            project_name   = project_name,
            policies_count = summary.get("policies_count", 0),
            services_count = summary.get("services_count", 0),
            gaps_total     = summary.get("gaps_total", 0),
        ))

        # Namespace
        out.append(_NAMESPACE.format(
            namespace=_slugify_namespace(project_name)
        ))

        # Actors block
        root_extra_diags = root.get("diagnostics", []) if root else []
        actor_graph = graph.get("actor_graph")
        if schema_version == "2.0" and actor_graph:
            actor_id_lines = "".join(
                f"  {an['id']}\n" for an in actor_graph.get("nodes", [])
            )
            out.append(_ACTORS_BLOCK_V2.format(
                actor_diagnostics = _format_diagnostics(root_extra_diags),
                actor_ids         = actor_id_lines,
            ))
        else:
            out.append(_ACTORS_BLOCK.format(
                actor_diagnostics=_format_diagnostics(root_extra_diags)
            ))

        # One policy block per module P node
        for p_node in module_p_nodes:
            p_diags = _format_diagnostics(p_node.get("diagnostics", []))
            out.append(_POLICY_OPEN.format(
                policy_name        = p_node.get("label", "UnknownPolicy"),
                policy_diagnostics = p_diags,
            ))

            # Rule placeholders (one per R node under this P)
            r_ids = [
                cid for cid in children_of.get(p_node["id"], [])
                if node_by_id.get(cid, {}).get("type") == "R"
            ]
            for r_id in r_ids:
                r_node  = node_by_id[r_id]
                r_diags = _format_diagnostics(r_node.get("diagnostics", []))
                out.append(_RULE_PLACEHOLDER.format(rule_diagnostics=r_diags))

            out.append(_POLICY_CLOSE)

        # Service blocks (one per S node)
        for s_node in [n for n in nodes if n["type"] == "S"]:
            meta   = s_node.get("meta", {})
            diags  = _format_diagnostics(s_node.get("diagnostics", []))
            out.append(_SERVICE_BLOCK.format(
                service_name        = s_node.get("label", "UnknownService"),
                source_name         = meta.get("source_name", "unknown"),
                line_number         = meta.get("line_number", "?"),
                service_diagnostics = diags,
            ))

        return "".join(out)
